### ISSUE TITLE
Create issue templates for our repos

### ISSUE THREAD

**Issue by hollsk** [pa11y/org#10]
Good issues are critical for being able to help users quickly. Github lets us create [issue templates](https://github.com/blog/2111-issue-and-pull-request-templates) to this end. Let's do that. 

In rough order of importance, we need templates for Pa11y, Pa11y Dashboard, Pa11y Webservice, and Pa11y CI at minimum. Some of our other repos could benefit from them, but those four are the most popular and the most likely place for issues to end up. 

We need to decide what info we'll need from people when they create issues. For all of them, I think it'll be useful to ask for:

```
Environment: [e.g. OS name/version, Node.js version, NPM version, version of whatever Pa11y tool is being used]
Steps to reproduce: [a list of steps to reproduce your bug]
Expected outcome: [what you expect to happen instead]
```

Can anybody think of anything else? 

We have a [related issue to improve logging](https://github.com/pa11y/pa11y/issues/241), so we can also ask for the output of the --version flag when that feature is complete.

**Comment by josebolos** [comment]
Awesome idea. Hopefully https://github.com/pa11y/pa11y/issues/241 will help us a bit with obtaining all the needed info straight away.

**Comment by rowanmanning** [comment]
Oh if we're gonna add these into the `.github` folder, should we also move `CONTRIBUTING.md` in there? It [works the same](https://help.github.com/articles/setting-guidelines-for-repository-contributors/), but can't decide whether people might want to easily get to it from the main repo view?

**Comment by josebolos** [comment]
I would say yes, move it. It should be linked from within the README in big red neon letters anyway, so I don't think that makes it harder to find.

I don't even remember when was the last time that I searched specifically for a `CONTRIBUTING.md` file instead of just searching in the README.

**Comment by andrewmee** [comment]
Just a note that `CONTRIBUTING.md` is picked up by GitHub as it currently is, so I think let's keep it where it is.

**Comment by josebolos** [comment]
This is now done.
