### ISSUE TITLE
Connectivity Pa11y

### ISSUE THREAD

**Issue by icarel** [pa11y/org#11]
Hi, you would need to know which ports are required to be open for the tool to work. I have seen that when you run the tasks it opens the ports: "9229", "55302", "61717" or "62604".
There is technical documentation about its operation.
Thanks and regards,
Icarel

**Comment by rowanmanning** [comment]
Hi @icarel. I'm not sure quite what you're asking for here. The ports are assigned randomly each time the tool is run so the ports above aren't always correct.

If you're asking for documentation on this, the correct repo to open an issue in is https://github.com/pa11y/pa11y

**Comment by icarel** [comment]
Hi,

Thank you!

I don't want to open an incident. I want to know what architecture the
application has. What ports do you open?
Is there documentation on this?

Thank you!
Regards,
Icarel

2017-06-30 11:14 GMT+02:00 Rowan Manning <notifications@github.com>:

**Comment by rowanmanning** [comment]
Oh, as mentioned above the ports opened are completely random

**Comment by icarel** [comment]
I want to know if you can have security problems, having so many ports open
..

Another query, I have tested the performance of Pa11y with more than 1000
tasks?

Thanks you!
Icarel

2017-06-30 11:35 GMT+02:00 Rowan Manning <notifications@github.com>:

**Comment by rowanmanning** [comment]
As mentioned before, this isn't the right place to ask questions about the individual Pa11y tools – here is the repo for technical queries https://github.com/pa11y/pa11y.

The ports Pa11y uses don't necessarily have to be exposed to the outside world, it just binds to them locally and doesn't use those ports for communicating externally.

I'm locking responses on this issue, feel free to ask further questions in a new issue on the main Pa11y repo. This one is for organisational stuff.
