### ISSUE TITLE
Rename repos

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/org#12]
After a Slack discussion the other day, I think we all agree that we should rename some of the repos:

- [x] [`ci`](https://github.com/pa11y/ci) to `pa11y-ci`
- [x] [`dashboard`](https://github.com/pa11y/dashboard) to `pa11y-dashboard`
- [x] [`lint-config`](https://github.com/pa11y/lint-config) to `pa11y-lint-config`
- [x] [`reporter-1.0-json`](https://github.com/pa11y/reporter-1.0-json) to `pa11y-reporter-1.0-json`
- [x] [`webservice-client-node`](https://github.com/pa11y/webservice-client-node) to `pa11y-webservice-client-node`
- [x] [`webservice`](https://github.com/pa11y/webservice) to `pa11y-webservice`

**Comment by hollsk** [comment]
All done 👍
