### ISSUE TITLE
Decide when the next meeting is going to be

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/org#2]
This was one of the outcomes of the 2016-05-06 meeting. We may be able to host it at Financial Times.

**Comment by sky-jack** [comment]
How about this Friday afternoon?

**Comment by hollsk** [comment]
Let's push this back to August as we've all got a _lot_ going on right now. I've set up a Doodle for us to decide on a date, location TBC: http://doodle.com/poll/psnvtgvcaxqviax9

**Comment by sky-jack** [comment]
Since everybody can do tomorrow, are we going to do it then?

**Comment by hollsk** [comment]
Yes! 11am, be there\* or be square. 

*we don't have a location yet 😁
