### ISSUE TITLE
Verify domain pa11y.org for GitHub

### ISSUE THREAD

**Issue by danyalaytekin** [pa11y/org#22]
We can acquire the flair `Verified` for this GitHub org and `pa11y.org` by adding one DNS text record to the domain.  I've started the process [here](https://github.com/organizations/pa11y/settings/domains).  @rowanmanning please could you click 'Continue verifying' and yoink the text record into the domain's DNS settings?

**Comment by rowanmanning** [comment]
Heya! Good to hear from you :) I'm pretty sure only Jude has access to the DNS records, should probs sort that

**Comment by danyalaytekin** [comment]
Hey! Thanks, you too 🥹  @dotcode, are you able to complete this?  Also importing @hollsk and @josebolos in case credentials propagated

**Comment by dotcode** [comment]
Ooh nice! Thanks. Have tweaked the DNS record. Ping me if it ain't verified by Monday …

**Comment by danyalaytekin** [comment]
It [came through](https://github.com/pa11y).  Thanks!
