### ISSUE TITLE
Rename repositories

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/org#4]
Since moving repos from Springer Nature, maybe we should rename some of the ones which repeat "Pa11y"?
- `pa11y/pa11y`: I'm personally OK with this
- `pa11y/pa11y-dashboard`: `pa11y/dashboard`?
- `pa11y/pa11y-reporter-1.0-json`: `pa11y/reporter-1.0-json`?
- `pa11y/pa11y-site`: Doesn't need renaming, will be removed in favour of the new site
- `pa11y/pa11y-webservice`: `pa11y/webservice`?
- `pa11y/pa11y-webservice-client-node`: `pa11y/webservice-client-node`?

**Comment by nickcall** [comment]
Agreed I think we should try and avoid the repeat

**Comment by hollsk** [comment]
happy with all these tbh

**Comment by andrewmee** [comment]
I think we should either rename all (except pa11y itself), or only rename projects that we plan to continue developing longterm.

**Comment by rowanmanning** [comment]
Cool. I might do some renaming over the weekend. Yet another find/replace in all the repos 😄

**Comment by rowanmanning** [comment]
I've renamed all of the repos and made necessary updates. Reviews would be much appreciated!
- [x] [Pa11y Dashboard](https://github.com/pa11y/dashboard/pull/136)
- [x] [Pa11y Reporter 1.0 JSON](https://github.com/pa11y/reporter-1.0-json/pull/2)
- [x] [Pa11y Sidekick](https://github.com/pa11y/sidekick/pull/23)
- [x] [Pa11y Webservice Node.js Client](https://github.com/pa11y/webservice-client-node/pull/5)
- [x] [Pa11y Webservice](https://github.com/pa11y/webservice/pull/28)
- [x] [Pa11y](https://github.com/pa11y/pa11y/pull/163)
- [x] [Website (New)](https://github.com/pa11y/pa11y.github.io/pull/31)
- [x] [Website (Old)](https://github.com/pa11y/pa11y-site/pull/7)

**Comment by andrewmee** [comment]
All renamed and resolved
