### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/org#5]
We've decided we need a new logo. A brief is outlined below and we'll discuss ideas here.

---
## Pa11y Logo Brief

We need a logo that encompasses the Pa11y projects.
### Requirements

Requirements for the logo, using MoSCoW (must = non-negotiable requirement, should = important but not a deal-breaker, could = nice to have).
- _Must_ be recognisable, and differentiate itself from other tools
- _Must_ be accessible
- _Must_ be inclusive (e.g. not be an obvious white dude)
- _Must_ work at small sizes (and also as a square for avatars etc)
- _Must_ be reproducible as an SVG
- _Should_ not focus too much on one kind of disability (e.g. blindness)
- _Could_ support a secondary line of text. E.g. Pa11y logo + "dashboard"
- _Could_ nod to the [old logo](http://pa11y.github.io/resources/brand/logo.svg) in terms of colours
### Existing Logos

Partly for inspiration, partly to make sure ours isn't too similar.
- [The A11Y Project](http://a11yproject.com/): Black circle with a white a11y man in it
- [a11y](https://github.com/addyosmani/a11y): A11Y written with little circles
- [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/): A checkmark
- [Chrome Accessibility Tools](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en): The a11y man in an orange cog
- [Wave](http://wave.webaim.org/): their little "W" on a green circle
- [HTML5 Accessibility](http://stevefaulkner.github.io/HTML5accessibility/): A big orange 5 with "a11y" underneath
- [JAWS](http://www.freedomscientific.com/Products/Blindness/JAWS): A shark that's speaking
- [Orca](https://wiki.gnome.org/Projects/Orca): An orca with a cane
- Apple: Blue circle with a white a11y man in it
### Word Association

A list of words that come to mind when you think of accessibility/Pa11y/a11y:

Open, Inclusive, Senses, Helpful, Supportive, Friend, Sidekick, Buddy, Helper, Partner, Equality, Jeremy Corbyn, Person, Human, Happiness, Diversity, FABULOUS, Universal, Fairness, Care Bears

**Comment by andrewmee** [comment]
I've had a play with this, starting with Rockwell and tweaking it to make it a little friendlier and quirkier, and to echo the 1 character form in the capital P to be used as a logomark:

![pa11y-rockwell-logo](https://cloud.githubusercontent.com/assets/24985/15572341/f76d3190-2337-11e6-9548-107e11fedc8e.png)

(third option is my proposal, just showing where it came from in the top two lines)

From here we could build the brand around the Rockwell font on the website and any other material also.

**Comment by alexkilgour** [comment]
Here is another idea we have been working up. It tries to retain the existing colours to create a "P" mark, with a subtle incorporation of "11" from Pa11y.

![idea-one](https://cloud.githubusercontent.com/assets/853933/15572446/94f7e4b4-2338-11e6-9f76-b15165fd5c16.png)

**Comment by alexkilgour** [comment]
We also tried closing the space between the 1's to try and make it clearer that it was a "P"

![idea-one-closed](https://cloud.githubusercontent.com/assets/853933/15572459/b1f87cea-2338-11e6-9518-a433cb6481cb.png)

**Comment by alexkilgour** [comment]
I am going to try and iterate on this idea to try and make it less "tall and thin"

**Comment by onishiweb** [comment]
Was toying round with the idea at lunch and finally figured out how to make it in Sketch. Takes on a bit of an emoji/cutesy approach but I think it fits quite well with some of the related words. Does need an awful lot of refining though (blame my terrible Sketch skills).

![pa11y-logo](https://cloud.githubusercontent.com/assets/1240073/15576834/bb7c5f34-2351-11e6-8994-6ab8fb64d4d4.jpg)

**Comment by rowanmanning** [comment]
@onishiweb: I like where you're going with the smily face :) definitely says "friendly". Thickening up the lines and a bit more uniformity would make it work better at smaller sizes I reckon, if anyone fancies trying that

**Comment by onishiweb** [comment]
Yep was thinking that too, I also don't like the harsh cut off at the ends of the "P" path, just couldn't find a way to sort that out in Sketch this time. Might spend some more time on it later this week, but if anyone wants to improve on it feel free.

**Comment by andrewmee** [comment]
I've made an attempt refining @howlingmad's fabulous P to close up the gap at the top but still keep a distinctive 1-shape.  Also shortening and widening it to be more square;

<img width="605" alt="screen shot 2016-05-26 at 16 45 20" src="https://cloud.githubusercontent.com/assets/24985/15580623/4606a6aa-2361-11e6-98fc-fa6879f9a1f6.png">

**Comment by alexkilgour** [comment]
I really like it. The only thing that jars for me is the top shadow. The shadow wouldn't cast like that, so doesn't look natural.

**Comment by alexkilgour** [comment]
maybe something like this? Sorry, I put the other shadow back! but i do like it, I think it gives a more 3d feel. I think if you remove it then you cannot have the yellow on red without removing the other shadow. it makes one bit look flat. You need the two shadows to show they are different 'objects', to give it the ribbon effect (imo obviously)

![screen shot 2016-05-26 at 16 51 58](https://cloud.githubusercontent.com/assets/853933/15580967/899b88c6-2362-11e6-891d-e7c87d5a6a84.png)

**Comment by rowanmanning** [comment]
I like it (the one Mee posted). This is gonna sound really fluffy (feel free to disagree) but the _only_ thing I'm not keen on is how angular it is. Was trying to think if there's a way to round some corners or make it a little less sharp. Essentially, it doesn't quite say "Care Bears" to me yet 😂

**Comment by andrewmee** [comment]
I like the sharpness of it.  It makes it look strong, sharp, and modern.  I can imagine that symbol on a pa11y-superhero's cape.  Or their [sidekick](https://github.com/pa11y/sidekick)'s?

**Comment by alexkilgour** [comment]
After consultation around the office, the consensus was on this version

![screen shot 2016-05-26 at 18 03 59](https://cloud.githubusercontent.com/assets/853933/15583193/b29702aa-236c-11e6-926a-ac10f183f8ad.png)

As it most clearly represents the P and the 11.

**Comment by rowanmanning** [comment]
That's the one I like most so far :)

**Comment by perryharlock** [comment]
A few of the above options with some roundedness for extra care bear :-)
![pa11y](https://cloud.githubusercontent.com/assets/1225142/15601777/44d2bd68-23e9-11e6-94e5-f1a4ac64ecb5.png)

**Comment by perryharlock** [comment]
Or....really round...for ultimate care bear
![pa11y-really-round](https://cloud.githubusercontent.com/assets/1225142/15601889/ee0850dc-23e9-11e6-8701-7863c8c8475a.png)

**Comment by rowanmanning** [comment]
The smaller amount of rounding I think could work. Deffo not keen on the super round Care Bear version though, is it just me or does it look like it might fall over? 😄

**Comment by perryharlock** [comment]
Yeah I concur Mr Manning. Not a big fan of the mega rounded version. But worth seeing it....

**Comment by alexkilgour** [comment]
Posting two versions of the logo. Square and rounded. Vote on your favourite via reactions!

**Comment by alexkilgour** [comment]
![square](https://cloud.githubusercontent.com/assets/853933/15604097/3bb288f0-23f6-11e6-92b0-6e10e9476e5a.png)

**Comment by alexkilgour** [comment]
![rounded](https://cloud.githubusercontent.com/assets/853933/15604103/48d2d224-23f6-11e6-8c30-ee69f05f243f.png)

**Comment by rowanmanning** [comment]
An update on this, we're currently going with a slightly modified version from the two that were voted on. The curved variant got the most votes both here and on Twitter, but a change was suggested by @tdhooper – we've removed the inner curves:

![pa11y](https://cloud.githubusercontent.com/assets/138944/15724034/2c11b498-283d-11e6-99d0-c5f99b9b7da3.png)

Side-by-side for comparison:

![pa11y-inner-curve-comparison](https://cloud.githubusercontent.com/assets/138944/15724076/623fa05c-283d-11e6-9c80-058f5a0d1dfb.png)

**Comment by rowanmanning** [comment]
@howlingmad: I've been doing some contrast checking with [Sim Daltonism](https://michelf.ca/projects/sim-daltonism/), I think we're _mostly_ OK but there are a few types of colour-blindness where the warning/error colours are really similar. With Monochromacy, the blue and red are also very similar.

Before we completely settle on these colours, is it worth seeing if these easy to fix? If not then I think we're OK as it's still an identifiable logo, we may just need to ensure that we clearly label things when these colours are used to highlight errors/warnings/notices :)

![pa11y-logo-contrast](https://cloud.githubusercontent.com/assets/138944/15724715/43591724-2840-11e6-9763-3257eb4e6c4f.png)

**Comment by rowanmanning** [comment]
Closing this, as we now have a new logo and have put it everywhere. Thanks for the work on this everyone!
